/* 
// Copyright 2015 Intel Corporation All Rights Reserved.
// 
// The source code, information and material ("Material") contained herein is
// owned by Intel Corporation or its suppliers or licensors, and title
// to such Material remains with Intel Corporation or its suppliers or
// licensors. The Material contains proprietary information of Intel
// or its suppliers and licensors. The Material is protected by worldwide
// copyright laws and treaty provisions. No part of the Material may be used,
// copied, reproduced, modified, published, uploaded, posted, transmitted,
// distributed or disclosed in any way without Intel's prior express written
// permission. No license under any patent, copyright or other intellectual
// property rights in the Material is granted to or conferred upon you,
// either expressly, by implication, inducement, estoppel or otherwise.
// Any license under such intellectual property rights must be express and
// approved by Intel in writing.
// 
// Unless otherwise agreed by Intel in writing,
// you may not remove or alter this notice or any other notice embedded in
// Materials by Intel or Intel's suppliers or licensors in any way.
// 
*/

#if !defined( __IPPAC_LEGACY_90_REDEFS_H__ )
#define __IPPAC_LEGACY_90_REDEFS_H__

#if !defined( __NO_IPPAC_LEGACY_90_REDEF )

#define ippsAnalysisFilterEncFree_SBR_32f legacy90ippsAnalysisFilterEncFree_SBR_32f
#define ippsAnalysisFilterEncGetSize_SBR_32f legacy90ippsAnalysisFilterEncGetSize_SBR_32f
#define ippsAnalysisFilterEncInitAlloc_SBR_32f legacy90ippsAnalysisFilterEncInitAlloc_SBR_32f
#define ippsAnalysisFilterEncInit_SBR_32f legacy90ippsAnalysisFilterEncInit_SBR_32f
#define ippsAnalysisFilterEnc_SBR_32f32fc legacy90ippsAnalysisFilterEnc_SBR_32f32fc
#define ippsAnalysisFilterFree_PQMF_MP3_32f legacy90ippsAnalysisFilterFree_PQMF_MP3_32f
#define ippsAnalysisFilterFree_SBRHQ_32s32sc legacy90ippsAnalysisFilterFree_SBRHQ_32s32sc
#define ippsAnalysisFilterFree_SBRLP_32s legacy90ippsAnalysisFilterFree_SBRLP_32s
#define ippsAnalysisFilterGetSize_PQMF_MP3_32f legacy90ippsAnalysisFilterGetSize_PQMF_MP3_32f
#define ippsAnalysisFilterGetSize_SBRHQ_32s32sc legacy90ippsAnalysisFilterGetSize_SBRHQ_32s32sc
#define ippsAnalysisFilterGetSize_SBRLP_32s legacy90ippsAnalysisFilterGetSize_SBRLP_32s
#define ippsAnalysisFilterGetSize_SBR_RToC_32f legacy90ippsAnalysisFilterGetSize_SBR_RToC_32f
#define ippsAnalysisFilterGetSize_SBR_RToC_32f32fc legacy90ippsAnalysisFilterGetSize_SBR_RToC_32f32fc
#define ippsAnalysisFilterGetSize_SBR_RToR_32f legacy90ippsAnalysisFilterGetSize_SBR_RToR_32f
#define ippsAnalysisFilterInitAlloc_PQMF_MP3_32f legacy90ippsAnalysisFilterInitAlloc_PQMF_MP3_32f
#define ippsAnalysisFilterInitAlloc_SBRHQ_32s32sc legacy90ippsAnalysisFilterInitAlloc_SBRHQ_32s32sc
#define ippsAnalysisFilterInitAlloc_SBRLP_32s legacy90ippsAnalysisFilterInitAlloc_SBRLP_32s
#define ippsAnalysisFilterInit_PQMF_MP3_32f legacy90ippsAnalysisFilterInit_PQMF_MP3_32f
#define ippsAnalysisFilterInit_SBRHQ_32s32sc legacy90ippsAnalysisFilterInit_SBRHQ_32s32sc
#define ippsAnalysisFilterInit_SBRLP_32s legacy90ippsAnalysisFilterInit_SBRLP_32s
#define ippsAnalysisFilterInit_SBR_RToC_32f legacy90ippsAnalysisFilterInit_SBR_RToC_32f
#define ippsAnalysisFilterInit_SBR_RToC_32f32fc legacy90ippsAnalysisFilterInit_SBR_RToC_32f32fc
#define ippsAnalysisFilterInit_SBR_RToR_32f legacy90ippsAnalysisFilterInit_SBR_RToR_32f
#define ippsAnalysisFilter_PQMF_MP3_32f legacy90ippsAnalysisFilter_PQMF_MP3_32f
#define ippsAnalysisFilter_PS_32fc_D2 legacy90ippsAnalysisFilter_PS_32fc_D2
#define ippsAnalysisFilter_SBRHQ_32s32sc legacy90ippsAnalysisFilter_SBRHQ_32s32sc
#define ippsAnalysisFilter_SBRLP_32s legacy90ippsAnalysisFilter_SBRLP_32s
#define ippsAnalysisFilter_SBR_RToC_32f32fc_D2L legacy90ippsAnalysisFilter_SBR_RToC_32f32fc_D2L
#define ippsAnalysisFilter_SBR_RToC_32f_D2L legacy90ippsAnalysisFilter_SBR_RToC_32f_D2L
#define ippsAnalysisFilter_SBR_RToR_32f_D2L legacy90ippsAnalysisFilter_SBR_RToR_32f_D2L
#define ippsAnalysisPQMF_MP3_16s32s legacy90ippsAnalysisPQMF_MP3_16s32s
#define ippsBitReservoirInit_MP3 legacy90ippsBitReservoirInit_MP3
#define ippsCalcSF_16s32f legacy90ippsCalcSF_16s32f
#define ippsDecodeChanPairElt_AAC legacy90ippsDecodeChanPairElt_AAC
#define ippsDecodeChanPairElt_MP4_AAC legacy90ippsDecodeChanPairElt_MP4_AAC
#define ippsDecodeDatStrElt_AAC legacy90ippsDecodeDatStrElt_AAC
#define ippsDecodeExtensionHeader_AAC legacy90ippsDecodeExtensionHeader_AAC
#define ippsDecodeFillElt_AAC legacy90ippsDecodeFillElt_AAC
#define ippsDecodeIsStereo_AAC_32s legacy90ippsDecodeIsStereo_AAC_32s
#define ippsDecodeMainHeader_AAC legacy90ippsDecodeMainHeader_AAC
#define ippsDecodeMsPNS_AAC_32s legacy90ippsDecodeMsPNS_AAC_32s
#define ippsDecodeMsStereo_AAC_32s_I legacy90ippsDecodeMsStereo_AAC_32s_I
#define ippsDecodePNS_AAC_32s legacy90ippsDecodePNS_AAC_32s
#define ippsDecodePrgCfgElt_AAC legacy90ippsDecodePrgCfgElt_AAC
#define ippsDecodeTNS_AAC_32s_I legacy90ippsDecodeTNS_AAC_32s_I
#define ippsDeinterleaveSpectrum_AAC_32s legacy90ippsDeinterleaveSpectrum_AAC_32s
#define ippsDeinterleave_16s legacy90ippsDeinterleave_16s
#define ippsDeinterleave_32f legacy90ippsDeinterleave_32f
#define ippsDetectTransient_SBR_32f legacy90ippsDetectTransient_SBR_32f
#define ippsEncodeTNS_AAC_32s_I legacy90ippsEncodeTNS_AAC_32s_I
#define ippsEstimateTNR_SBR_32f legacy90ippsEstimateTNR_SBR_32f
#define ippsFDPFree_32f legacy90ippsFDPFree_32f
#define ippsFDPFwd_32f legacy90ippsFDPFwd_32f
#define ippsFDPGetSize_32f legacy90ippsFDPGetSize_32f
#define ippsFDPInitAlloc_32f legacy90ippsFDPInitAlloc_32f
#define ippsFDPInit_32f legacy90ippsFDPInit_32f
#define ippsFDPInv_32f_I legacy90ippsFDPInv_32f_I
#define ippsFDPResetGroup_32f legacy90ippsFDPResetGroup_32f
#define ippsFDPResetSfb_32f legacy90ippsFDPResetSfb_32f
#define ippsFDPReset_32f legacy90ippsFDPReset_32f
#define ippsFIRBlockFree_32f legacy90ippsFIRBlockFree_32f
#define ippsFIRBlockInitAlloc_32f legacy90ippsFIRBlockInitAlloc_32f
#define ippsFIRBlockOne_32f legacy90ippsFIRBlockOne_32f
#define ippsHuffmanDecodeSfbMbp_MP3_1u32s legacy90ippsHuffmanDecodeSfbMbp_MP3_1u32s
#define ippsHuffmanDecodeSfb_MP3_1u32s legacy90ippsHuffmanDecodeSfb_MP3_1u32s
#define ippsHuffmanDecode_MP3_1u32s legacy90ippsHuffmanDecode_MP3_1u32s
#define ippsHuffmanEncode_MP3_32s1u legacy90ippsHuffmanEncode_MP3_32s1u
#define ippsInterleave_16s legacy90ippsInterleave_16s
#define ippsInterleave_32f legacy90ippsInterleave_32f
#define ippsJoin_32f16s_D2L legacy90ippsJoin_32f16s_D2L
#define ippsJointStereoEncode_MP3_32s_I legacy90ippsJointStereoEncode_MP3_32s_I
#define ippsLongTermPredict_AAC_32s legacy90ippsLongTermPredict_AAC_32s
#define ippsLongTermReconstruct_AAC_32s legacy90ippsLongTermReconstruct_AAC_32s
#define ippsLtpUpdate_AAC_32s legacy90ippsLtpUpdate_AAC_32s
#define ippsMDCTFwdFree_16s legacy90ippsMDCTFwdFree_16s
#define ippsMDCTFwdFree_32f legacy90ippsMDCTFwdFree_32f
#define ippsMDCTFwdGetBufSize_16s legacy90ippsMDCTFwdGetBufSize_16s
#define ippsMDCTFwdGetBufSize_32f legacy90ippsMDCTFwdGetBufSize_32f
#define ippsMDCTFwdGetSize_16s legacy90ippsMDCTFwdGetSize_16s
#define ippsMDCTFwdGetSize_32f legacy90ippsMDCTFwdGetSize_32f
#define ippsMDCTFwdInitAlloc_16s legacy90ippsMDCTFwdInitAlloc_16s
#define ippsMDCTFwdInitAlloc_32f legacy90ippsMDCTFwdInitAlloc_32f
#define ippsMDCTFwdInit_16s legacy90ippsMDCTFwdInit_16s
#define ippsMDCTFwdInit_32f legacy90ippsMDCTFwdInit_32f
#define ippsMDCTFwd_16s_Sfs legacy90ippsMDCTFwd_16s_Sfs
#define ippsMDCTFwd_32f legacy90ippsMDCTFwd_32f
#define ippsMDCTFwd_32f_I legacy90ippsMDCTFwd_32f_I
#define ippsMDCTFwd_AAC_32s legacy90ippsMDCTFwd_AAC_32s
#define ippsMDCTFwd_AAC_32s_I legacy90ippsMDCTFwd_AAC_32s_I
#define ippsMDCTFwd_MP3_32s legacy90ippsMDCTFwd_MP3_32s
#define ippsMDCTInvFree_32f legacy90ippsMDCTInvFree_32f
#define ippsMDCTInvGetBufSize_32f legacy90ippsMDCTInvGetBufSize_32f
#define ippsMDCTInvGetSize_32f legacy90ippsMDCTInvGetSize_32f
#define ippsMDCTInvInitAlloc_32f legacy90ippsMDCTInvInitAlloc_32f
#define ippsMDCTInvInit_32f legacy90ippsMDCTInvInit_32f
#define ippsMDCTInvWindow_MP3_32s legacy90ippsMDCTInvWindow_MP3_32s
#define ippsMDCTInv_32f legacy90ippsMDCTInv_32f
#define ippsMDCTInv_32f_I legacy90ippsMDCTInv_32f_I
#define ippsMDCTInv_AAC_32s16s legacy90ippsMDCTInv_AAC_32s16s
#define ippsMDCTInv_AAC_32s_I legacy90ippsMDCTInv_AAC_32s_I
#define ippsMDCTInv_MP3_32s legacy90ippsMDCTInv_MP3_32s
#define ippsMakeFloat_16s32f legacy90ippsMakeFloat_16s32f
#define ippsNoiselessDecode_AAC legacy90ippsNoiselessDecode_AAC
#define ippsNoiselessDecoder_LC_AAC legacy90ippsNoiselessDecoder_LC_AAC
#define ippsPackFrameHeader_MP3 legacy90ippsPackFrameHeader_MP3
#define ippsPackScaleFactors_MP3_8s1u legacy90ippsPackScaleFactors_MP3_8s1u
#define ippsPackSideInfo_MP3 legacy90ippsPackSideInfo_MP3
#define ippsPow34_16s_Sfs legacy90ippsPow34_16s_Sfs
#define ippsPow34_32f legacy90ippsPow34_32f
#define ippsPow34_32f16s legacy90ippsPow34_32f16s
#define ippsPow43Scale_16s32s_Sf legacy90ippsPow43Scale_16s32s_Sf
#define ippsPow43_16s32f legacy90ippsPow43_16s32f
#define ippsPredictCoef_SBR_C_32f_D2L legacy90ippsPredictCoef_SBR_C_32f_D2L
#define ippsPredictCoef_SBR_C_32fc_D2L legacy90ippsPredictCoef_SBR_C_32fc_D2L
#define ippsPredictCoef_SBR_R_32f_D2L legacy90ippsPredictCoef_SBR_R_32f_D2L
#define ippsPredictOneCoef_SBRHQ_32sc_D2L legacy90ippsPredictOneCoef_SBRHQ_32sc_D2L
#define ippsPredictOneCoef_SBRLP_32s_D2L legacy90ippsPredictOneCoef_SBRLP_32s_D2L
#define ippsPsychoacousticModelTwo_MP3_16s legacy90ippsPsychoacousticModelTwo_MP3_16s
#define ippsQuantInv_AAC_32s_I legacy90ippsQuantInv_AAC_32s_I
#define ippsQuantize_MP3_32s_I legacy90ippsQuantize_MP3_32s_I
#define ippsReQuantizeSfb_MP3_32s_I legacy90ippsReQuantizeSfb_MP3_32s_I
#define ippsReQuantize_MP3_32s_I legacy90ippsReQuantize_MP3_32s_I
#define ippsScale_32f_I legacy90ippsScale_32f_I
#define ippsSpread_16s_Sfs legacy90ippsSpread_16s_Sfs
#define ippsSynthPQMF_MP3_32s16s legacy90ippsSynthPQMF_MP3_32s16s
#define ippsSynthesisDownFilterFree_SBRHQ_32sc32s legacy90ippsSynthesisDownFilterFree_SBRHQ_32sc32s
#define ippsSynthesisDownFilterFree_SBRLP_32s legacy90ippsSynthesisDownFilterFree_SBRLP_32s
#define ippsSynthesisDownFilterGetSize_SBRHQ_32sc32s legacy90ippsSynthesisDownFilterGetSize_SBRHQ_32sc32s
#define ippsSynthesisDownFilterGetSize_SBRLP_32s legacy90ippsSynthesisDownFilterGetSize_SBRLP_32s
#define ippsSynthesisDownFilterGetSize_SBR_CToR_32f legacy90ippsSynthesisDownFilterGetSize_SBR_CToR_32f
#define ippsSynthesisDownFilterGetSize_SBR_CToR_32fc32f legacy90ippsSynthesisDownFilterGetSize_SBR_CToR_32fc32f
#define ippsSynthesisDownFilterGetSize_SBR_RToR_32f legacy90ippsSynthesisDownFilterGetSize_SBR_RToR_32f
#define ippsSynthesisDownFilterInitAlloc_SBRHQ_32sc32s legacy90ippsSynthesisDownFilterInitAlloc_SBRHQ_32sc32s
#define ippsSynthesisDownFilterInitAlloc_SBRLP_32s legacy90ippsSynthesisDownFilterInitAlloc_SBRLP_32s
#define ippsSynthesisDownFilterInit_SBRHQ_32sc32s legacy90ippsSynthesisDownFilterInit_SBRHQ_32sc32s
#define ippsSynthesisDownFilterInit_SBRLP_32s legacy90ippsSynthesisDownFilterInit_SBRLP_32s
#define ippsSynthesisDownFilterInit_SBR_CToR_32f legacy90ippsSynthesisDownFilterInit_SBR_CToR_32f
#define ippsSynthesisDownFilterInit_SBR_CToR_32fc32f legacy90ippsSynthesisDownFilterInit_SBR_CToR_32fc32f
#define ippsSynthesisDownFilterInit_SBR_RToR_32f legacy90ippsSynthesisDownFilterInit_SBR_RToR_32f
#define ippsSynthesisDownFilter_SBRHQ_32sc32s legacy90ippsSynthesisDownFilter_SBRHQ_32sc32s
#define ippsSynthesisDownFilter_SBRLP_32s legacy90ippsSynthesisDownFilter_SBRLP_32s
#define ippsSynthesisDownFilter_SBR_CToR_32f_D2L legacy90ippsSynthesisDownFilter_SBR_CToR_32f_D2L
#define ippsSynthesisDownFilter_SBR_CToR_32fc32f_D2L legacy90ippsSynthesisDownFilter_SBR_CToR_32fc32f_D2L
#define ippsSynthesisDownFilter_SBR_RToR_32f_D2L legacy90ippsSynthesisDownFilter_SBR_RToR_32f_D2L
#define ippsSynthesisFilterFree_DTS_32f legacy90ippsSynthesisFilterFree_DTS_32f
#define ippsSynthesisFilterFree_PQMF_MP3_32f legacy90ippsSynthesisFilterFree_PQMF_MP3_32f
#define ippsSynthesisFilterFree_SBRHQ_32sc32s legacy90ippsSynthesisFilterFree_SBRHQ_32sc32s
#define ippsSynthesisFilterFree_SBRLP_32s legacy90ippsSynthesisFilterFree_SBRLP_32s
#define ippsSynthesisFilterGetSize_DTS_32f legacy90ippsSynthesisFilterGetSize_DTS_32f
#define ippsSynthesisFilterGetSize_PQMF_MP3_32f legacy90ippsSynthesisFilterGetSize_PQMF_MP3_32f
#define ippsSynthesisFilterGetSize_SBRHQ_32sc32s legacy90ippsSynthesisFilterGetSize_SBRHQ_32sc32s
#define ippsSynthesisFilterGetSize_SBRLP_32s legacy90ippsSynthesisFilterGetSize_SBRLP_32s
#define ippsSynthesisFilterGetSize_SBR_CToR_32f legacy90ippsSynthesisFilterGetSize_SBR_CToR_32f
#define ippsSynthesisFilterGetSize_SBR_CToR_32fc32f legacy90ippsSynthesisFilterGetSize_SBR_CToR_32fc32f
#define ippsSynthesisFilterGetSize_SBR_RToR_32f legacy90ippsSynthesisFilterGetSize_SBR_RToR_32f
#define ippsSynthesisFilterInitAlloc_DTS_32f legacy90ippsSynthesisFilterInitAlloc_DTS_32f
#define ippsSynthesisFilterInitAlloc_PQMF_MP3_32f legacy90ippsSynthesisFilterInitAlloc_PQMF_MP3_32f
#define ippsSynthesisFilterInitAlloc_SBRHQ_32sc32s legacy90ippsSynthesisFilterInitAlloc_SBRHQ_32sc32s
#define ippsSynthesisFilterInitAlloc_SBRLP_32s legacy90ippsSynthesisFilterInitAlloc_SBRLP_32s
#define ippsSynthesisFilterInit_DTS_32f legacy90ippsSynthesisFilterInit_DTS_32f
#define ippsSynthesisFilterInit_PQMF_MP3_32f legacy90ippsSynthesisFilterInit_PQMF_MP3_32f
#define ippsSynthesisFilterInit_SBRHQ_32sc32s legacy90ippsSynthesisFilterInit_SBRHQ_32sc32s
#define ippsSynthesisFilterInit_SBRLP_32s legacy90ippsSynthesisFilterInit_SBRLP_32s
#define ippsSynthesisFilterInit_SBR_CToR_32f legacy90ippsSynthesisFilterInit_SBR_CToR_32f
#define ippsSynthesisFilterInit_SBR_CToR_32fc32f legacy90ippsSynthesisFilterInit_SBR_CToR_32fc32f
#define ippsSynthesisFilterInit_SBR_RToR_32f legacy90ippsSynthesisFilterInit_SBR_RToR_32f
#define ippsSynthesisFilter_DTS_32f legacy90ippsSynthesisFilter_DTS_32f
#define ippsSynthesisFilter_PQMF_MP3_32f legacy90ippsSynthesisFilter_PQMF_MP3_32f
#define ippsSynthesisFilter_SBRHQ_32sc32s legacy90ippsSynthesisFilter_SBRHQ_32sc32s
#define ippsSynthesisFilter_SBRLP_32s legacy90ippsSynthesisFilter_SBRLP_32s
#define ippsSynthesisFilter_SBR_CToR_32f_D2L legacy90ippsSynthesisFilter_SBR_CToR_32f_D2L
#define ippsSynthesisFilter_SBR_CToR_32fc32f_D2L legacy90ippsSynthesisFilter_SBR_CToR_32fc32f_D2L
#define ippsSynthesisFilter_SBR_RToR_32f_D2L legacy90ippsSynthesisFilter_SBR_RToR_32f_D2L
#define ippsUnpackADIFHeader_AAC legacy90ippsUnpackADIFHeader_AAC
#define ippsUnpackADTSFrameHeader_AAC legacy90ippsUnpackADTSFrameHeader_AAC
#define ippsUnpackFrameHeader_MP3 legacy90ippsUnpackFrameHeader_MP3
#define ippsUnpackScaleFactors_MP3_1u8s legacy90ippsUnpackScaleFactors_MP3_1u8s
#define ippsUnpackSideInfo_MP3 legacy90ippsUnpackSideInfo_MP3
#define ippsVLCCountBits_16s32s legacy90ippsVLCCountBits_16s32s
#define ippsVLCCountEscBits_AAC_16s32s legacy90ippsVLCCountEscBits_AAC_16s32s
#define ippsVLCCountEscBits_MP3_16s32s legacy90ippsVLCCountEscBits_MP3_16s32s
#define ippsVLCDecodeBlock_1u16s legacy90ippsVLCDecodeBlock_1u16s
#define ippsVLCDecodeEscBlock_AAC_1u16s legacy90ippsVLCDecodeEscBlock_AAC_1u16s
#define ippsVLCDecodeEscBlock_MP3_1u16s legacy90ippsVLCDecodeEscBlock_MP3_1u16s
#define ippsVLCDecodeFree_32s legacy90ippsVLCDecodeFree_32s
#define ippsVLCDecodeGetSize_32s legacy90ippsVLCDecodeGetSize_32s
#define ippsVLCDecodeInitAlloc_32s legacy90ippsVLCDecodeInitAlloc_32s
#define ippsVLCDecodeInit_32s legacy90ippsVLCDecodeInit_32s
#define ippsVLCDecodeOne_1u16s legacy90ippsVLCDecodeOne_1u16s
#define ippsVLCDecodeUTupleBlock_1u16s legacy90ippsVLCDecodeUTupleBlock_1u16s
#define ippsVLCDecodeUTupleEscBlock_AAC_1u16s legacy90ippsVLCDecodeUTupleEscBlock_AAC_1u16s
#define ippsVLCDecodeUTupleEscBlock_MP3_1u16s legacy90ippsVLCDecodeUTupleEscBlock_MP3_1u16s
#define ippsVLCDecodeUTupleFree_32s legacy90ippsVLCDecodeUTupleFree_32s
#define ippsVLCDecodeUTupleGetSize_32s legacy90ippsVLCDecodeUTupleGetSize_32s
#define ippsVLCDecodeUTupleInitAlloc_32s legacy90ippsVLCDecodeUTupleInitAlloc_32s
#define ippsVLCDecodeUTupleInit_32s legacy90ippsVLCDecodeUTupleInit_32s
#define ippsVLCDecodeUTupleOne_1u16s legacy90ippsVLCDecodeUTupleOne_1u16s
#define ippsVLCEncodeBlock_16s1u legacy90ippsVLCEncodeBlock_16s1u
#define ippsVLCEncodeEscBlock_AAC_16s1u legacy90ippsVLCEncodeEscBlock_AAC_16s1u
#define ippsVLCEncodeEscBlock_MP3_16s1u legacy90ippsVLCEncodeEscBlock_MP3_16s1u
#define ippsVLCEncodeFree_32s legacy90ippsVLCEncodeFree_32s
#define ippsVLCEncodeGetSize_32s legacy90ippsVLCEncodeGetSize_32s
#define ippsVLCEncodeInitAlloc_32s legacy90ippsVLCEncodeInitAlloc_32s
#define ippsVLCEncodeInit_32s legacy90ippsVLCEncodeInit_32s
#define ippsVLCEncodeOne_16s1u legacy90ippsVLCEncodeOne_16s1u
#define ippsVQCodeBookFree_32f legacy90ippsVQCodeBookFree_32f
#define ippsVQCodeBookGetSize_32f legacy90ippsVQCodeBookGetSize_32f
#define ippsVQCodeBookInitAlloc_32f legacy90ippsVQCodeBookInitAlloc_32f
#define ippsVQCodeBookInit_32f legacy90ippsVQCodeBookInit_32f
#define ippsVQIndexSelect_32f legacy90ippsVQIndexSelect_32f
#define ippsVQMainSelect_32f legacy90ippsVQMainSelect_32f
#define ippsVQPreliminarySelect_32f legacy90ippsVQPreliminarySelect_32f
#define ippsVQReconstruction_32f legacy90ippsVQReconstruction_32f

#endif /* __NO_IPPAC_LEGACY_90_REDEF   */
#endif /* __IPPAC_LEGACY_90_REDEFS_H__ */

